### ISSUE TITLE
SIGSEGV on Raft initial configuration

### ISSUE THREAD

**Issue by CameronNemo** [CanonicalLtd/dqlite#96]
Hello,

I am not sure if this is the right project to submit the issue for, but here it goes: I tried to install LXD using dqlite and a replication enabled sqlite. Unfortunately, running the daemon results in a segfault: http://ix.io/1saK

dqlite was built using a standard autoreconf / configure / make.

sqlite-replication was built with the following configure arguments:

    --enable-replication --enable-threadsafe --enable-dynamic-extensions --enable-fts5

and the following CFLAGS:

```
-DSQLITE_ENABLE_DBSTAT_VTAB
-DSQLITE_ENABLE_COLUMN_METADATA
-DSQLITE_ENABLE_UNLOCK_NOTIFY
-DSQLITE_SECURE_DELETE
-DSQLITE_ENABLE_JSON1
-DSQLITE_ENABLE_FTS3
-DSQLITE_ENABLE_FTS3_PARENTHESIS
-DSQLITE_ENABLE_FTS4
-DSQLITE_ENABLE_FTS3_TOKENIZER=1
-DSQLITE_ENABLE_BATCH_ATOMIC_WRITE=1
-DHAVE_FDATASYNC
```

Please let me know if there is anything I can do to get more information about this segfault.

Some background on the host:

* distro: Void Linux
* libedit: 20180525.3.1_2
* libuv: 1.24.0
* sqlite-replication: 3.25.3
* dqlite: 0.2.5
* lxd: tried on both 3.7 and 3.0.2

**Comment by freeekanayaka** [comment]
Hello,

from the CFLAGS you pasted it seems that sqlite is not built with replication support (there should e ```-DSQLITE_ENABLE_WAL_REPLICATION``` in there). What tarball did you download? Maybe you need to pass ```--enable-wal-replication``` instead of ```--enable-replication```.

**Comment by CameronNemo** [comment]
Thank you for the tips. I went back and checked each step of the build. It appears as though sqlite was being built with replication support, but LXD and/or dqlite was not being properly linked to the replication enabled sqlite. Serves me right for not using the LXD Makefile! Everything is working now, I suspect due to passing the right Go tags to the LXD build.
