### ISSUE TITLE
configure fail with syntax error

### ISSUE THREAD

**Issue by PinkD** [CanonicalLtd/dqlite#97]
when i tried to build [lxd](https://github.com/lxc/lxd), `make deps` failed when running `./configure` :

```
./configure: line 9746: syntax error near unexpected token `SQLITE,'
./configure: line 9746: `PKG_CHECK_MODULES(SQLITE, sqlite3 >= 3.22.0, , )'
```

the code ref is https://github.com/lxc/lxd/blob/master/Makefile#L59

where should this token `SQLITE` be init/create? 

I tried to comment those `PKG_CHECK_MODULES` lines in the `configure` file, and the configuration was going to succeed. but it's complicated to do this when packaging automatically

btw, all the deps except `sqlite3` had already been installed, and [sqlite](https://github.com/CanonicalLtd/sqlite) was compiled manually and going to be static linked

OS: ArchLinux in lxd (newest version)

maybe i should not compile it in the container?

**Comment by freeekanayaka** [comment]
Hm, that's weird. There's no such snippet as the one you pasted (```PKG_CHECK_MODULES(SQLITE, sqlite3 >= 3.22.0, , )``` in the ```configure``` that ```autoreconf -i``` generates here (on Ubuntu). Maybe you're missing some dependency that confuses autoconf. What does:

```
which pkg-config 
```

Say?

@monstermunchkin might be able to help too, since he has packaged LXD for ArchLinux, afaik.

**Comment by monstermunchkin** [comment]
> Hm, that's weird. There's no such snippet as the one you pasted (PKG_CHECK_MODULES(SQLITE, sqlite3 >= 3.22.0, , ) in the configure that autoreconf -i generates here (on Ubuntu).

Same here. It builds fine on Arch and also in an Arch container.

**Comment by PinkD** [comment]
> Hm, that's weird. There's no such snippet as the one you pasted (`PKG_CHECK_MODULES(SQLITE, sqlite3 >= 3.22.0, , )` in the `configure` that `autoreconf -i` generates here (on Ubuntu). Maybe you're missing some dependency that confuses autoconf. What does:
> 
> ```
> which pkg-config 
> ```
> Say?
> 
> @monstermunchkin might be able to help too, since he has packaged LXD for ArchLinux, afaik.

oh, it's really sorry. I found that i had not installed `pkg-config` in the container and the PKGBUILD either would not tell me about that. 
PKGBUILD's makedepends has a principle that [Members of base-devel group should not be included in makedepends array](https://wiki.archlinux.org/index.php/PKGBUILD#makedepends)
I should have read the wiki again before using `makepkg`

Since I've found the solution, I'm gonna close this issue, thanks a lot
